import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true,executablePath:process.env.LOCALAPPDATA+'/ms-playwright/chromium-1234/chrome-win64/chrome.exe',args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage();
page.on('pageerror',e=>console.log('PAGE ERROR',e.name,e.message,e.stack));
page.on('requestfailed',r=>console.log('REQUEST FAILED',r.url(),r.failure()));
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
await page.goto('http://localhost:4173/',{waitUntil:'networkidle'});
await page.waitForTimeout(2500);
console.log('SCENES',await page.locator('.scene').count());
console.log('IMPORT',await page.evaluate(async()=>{try{await import('./app.js');return 'ok';}catch(e){return {name:e.name,message:e.message,stack:e.stack};}}));
await browser.close();
